drm/img-rogue: fix build with gcc 16
GCC 16 now complains about initialized/assigned but unused variables.
Only define/set them if the relevant defines are set.

Fixes:
mmu_common.c:3038:20: error: variable 'ui32MappedCount' set but not used [-Werror=unused-but-set-variable=]
 3038 |         IMG_UINT32 ui32MappedCount = 0;

sync_checkpoint.c:3094:40: error: variable 'ui32NullScpCount' set but not used [-Werror=unused-but-set-variable=]
 3094 |         IMG_UINT32 ui32ItemsFreed = 0, ui32NullScpCount = 0, __maybe_unused ui32PoolCount;

rgxhwperf_common.c:3503:41: error: variable 'ui32TlPackets' set but not used [-Werror=unused-but-set-variable=]
 3503 |         IMG_UINT32                      ui32TlPackets = 0;

Signed-off-by: Max Krummenacher <max.oss.09@gmail.com>